# Generated by Django 5.1.2 on 2025-05-27 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Leito",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.PositiveIntegerField(unique=True)),
                ("ocupado", models.BooleanField(default=False)),
                (
                    "paciente_nome",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("paciente_idade", models.PositiveIntegerField(blank=True, null=True)),
                ("data_internacao", models.DateField(blank=True, null=True)),
                ("motivo", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
